remote_theme: mmistakes/so-simple-theme
#remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"

locale: en-US
title: ""
subtitle: "" 
description: ""
baseurl: "/SeminaireInformatiqueUSherbrooke"
github_username: alexandremercieraubin
url: 'https://alexandremercieraubin.com'
date_format: "%B %-d, %Y"
mathjax:
  enable: true
  combo: "tex-svg"
  tags: "none" # 'ams' automatically label math equations
google_fonts:
  - name: "Source Serif 4"
    weights: "400,400i,700,700i"
  #- name: "Source Sans Pro"
  #  weights: "400,400i,700,700i"

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:categories/:title/
markdown: kramdown
kramdown: 
  math_engine: mathjax
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/
pagination:
  # ...
  sort_field: "stickiness"
  sort_reverse: false
  
# Search
search_full_content: false

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

stickyposts:
  enabled: true   # Enable StickyPosts; default: true
  debug: true       # Show additional info; default: false
  sort: "date"      # Optional sort field; default: "date", use "none" to avoid sorting
  reverse: true     # Ascending order, default: false
  retain: true      # Also show sticky posts in their original positions; default: false
  reverse_sticky: true    # Reverse the order of the sticky posts, e.g. oldest first; default: false

  #collection: articles   # The collection to "stickify"; default "posts"

  # Or multiple collections:
  collections:
  - posts

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from

# Collections
collections:
  cheatsheets:
    output: true
    permalink: /:collection/:path/

# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true
